### ISSUE TITLE
Incorporate relaton documentation from csd-citation-models

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton.com#13]
The documentation on relaton.com is ... unacceptable.

There is extensive documentation I wrote on relaton for csd-citation-models. The repository for this seems to have disappeared. This documentation, one way or another, needs to end up on relaton.com. There is right now no public document explaining the relaton document relations for example.

I have zero interest in rewriting the documentation I have already written. I have high interest in getting it publicly visible.

If you don't have a copy of csd-citation-models any more, contact me.

**Comment by opoudjis** [comment]
Triggered by https://github.com/relaton/relaton-models/issues/22 and https://github.com/relaton/relaton-models/issues/23. We can't have public discussions of Relaton support of relations without public documentation.

**Comment by ronaldtse** [comment]
@opoudjis csd-citation-models has been moved here: https://gitlab.com/calconnect/tc-publish/csd-citation-models

**Comment by ronaldtse** [comment]
@opoudjis please feel free to copy out the content to relaton.com for this purpose.

**Comment by opoudjis** [comment]
I'm going to copy the x-*.adoc files to relaton.com, as they are expressly documentation of relaton and not iso690; the documentation in the body of the document, I think, would be overkill for relaton.com

**Comment by ronaldtse** [comment]
@opoudjis whatever appropriate is good. In fact, I'd think all of that content should be available on relaton.com, as long as the structure is logically understandable by readers.

**Comment by opoudjis** [comment]
There are a dozen files, and while I will just dump them into relaton.com, that... will look crap. Someone will need to take care of presentation; unfortunately that can't be me...

**Comment by opoudjis** [comment]
Need to add a document more explicitly documenting the citation model.

**Comment by opoudjis** [comment]
Done. Will need @strogonoff to clean up.
