### ISSUE TITLE
Review asciibib documentation

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton.com#17]
AsciiBib/Relaton YAML is a fairly unforgiving markup, because it is a direct mapping to Relaton XML.

Request that you review the examples in https://github.com/relaton/relaton.com/blob/master/_specs/asciibib.adoc and https://github.com/relaton/relaton.com/blob/master/_specs/relaton-yaml.adoc, and fill in any missing attributes; for example, contributor roles were missing in examples I've written.

**Comment by ronaldtse** [comment]
This already breaks because the  `contributor.role:: author` is missing. I think contributor should provide a default role of `author`, and if a role is not provided but the contributor.person is, we should raise a WARNING.

```
[%bibitem]
== Monty Python and the Holy Grail
id:: grail_film
contributor::
contributor.person.name.initial:: G.
contributor.person.name.surname:: Chapman
contributor::
contributor.person.name.initial:: J.
contributor.person.name.surname:: Cleese
contributor::
contributor.person.name.initial:: E.
contributor.person.name.surname:: Idle
contributor::
contributor.person.name.initial:: T.
contributor.person.name.surname:: Gilliam
contributor::
contributor.person.name.initial:: T.
contributor.person.name.surname:: Jones
contributor::
contributor.person.name.initial:: M.
contributor.person.name.surname:: Palin
date::
date.type:: published
date.value:: 1975
```

**Comment by andrew2net** [comment]
> I think contributor should provide a default role of `author`, and if a role is not provided but the contributor.person is, we should raise a WARNING.

@ronaldtse now we have a default role `publisher`. Should we add a default role `author` for persons and keep `publisher` for organizations?
I think we don't need raise a WARNING if we set a default role.

**Comment by ronaldtse** [comment]
@andrew2net agree. Let's do that.
