### ISSUE TITLE
Describe bibliography types supported by Relaton reference implementation

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton.com#5]
Relaton today supports the following citations for auto-fetching:

* ISO
* IETF
* IEC
* NIST
* Chinese standards
* OGC
* ITU-T

We should list them out like how we do with Metanorma flavors.

**Comment by ronaldtse** [comment]
Each of these have a particular way of fetching.

These are the gems:

https://github.com/riboseinc/nistbib
https://github.com/riboseinc/isobib
https://github.com/riboseinc/iecbib
https://github.com/riboseinc/gbbib
https://github.com/riboseinc/ietfbib

**Comment by ronaldtse** [comment]
Ping @strogonoff assign to yourself please 👍

**Comment by strogonoff** [comment]
Done in https://github.com/relaton/relaton.com/commit/47dcc32da56af99596f9601cdc119cede9f228d4.

Will add instruction about adding new bibliography type in README shortly

**Comment by strogonoff** [comment]
Regarding end-user documentation, waiting for 1:1. I believe most users will not have to deal with Relaton directly (they’ll be using it implicitly through Metanorma), and for those who will have to deal with it I’d like to hash out who and how.
