### ISSUE TITLE
Guidance to AsciiBib needs to be published

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton.com#8]
https://github.com/relaton/relaton-bib/blob/master/docs/hash.adoc needs to end up somewhere public-facing, and I have just alluded to it in documenting metanorma-ietf. Either it goes to metanorma.com, or it goes to relaton.com, with clear links from metanorma.com.

This arguably applies to all the documentation still under relaton gems, such as https://github.com/relaton/relaton-cli/tree/master/docs and https://github.com/relaton/relaton/tree/master/docs ; but AsciiBib specifically is pressing for metanorma.

**Comment by opoudjis** [comment]
Wait on https://github.com/metanorma/metanorma.com/issues/200

**Comment by opoudjis** [comment]
Reviewed. Please proceed.

**Comment by ronaldtse** [comment]
@opoudjis this is actionable now. How do you want this to be published? Ping @strogonoff ?

**Comment by ronaldtse** [comment]
@andrew2net can you please help with this? Tanks.
